name: Static Analysis

on:
  push:
    branches:
    - master
    - rel-*
  pull_request:
    branches:
    - master
    - rel-*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'pull_request' && github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  detect-dupes:
    name: Detect duplicate functions
    runs-on: ubuntu-24.04
    steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Min composer version
        coverage: none

    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Run detector
      run: php -d memory_limit=1g cli/findDuplicateFunctions.php
